{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 0,
   "metadata": {
    "application/vnd.databricks.v1+cell": {
     "cellMetadata": {},
     "inputWidgets": {},
     "nuid": "34c0e5aa-a7a5-4e8f-a0fb-67eebcf5cad3",
     "showTitle": false,
     "tableResultSettingsMap": {},
     "title": ""
    }
   },
   "outputs": [],
   "source": [
    "import dlt\n",
    "from pyspark.sql import functions as F\n",
    "from pyspark.sql.window import Window\n",
    "\n",
    "\n",
    "@dlt.table(\n",
    "    name=\"kpi_enriched\",\n",
    "    comment=\"Cleaned and enriched KPIs with QoQ deltas and quality flags\",\n",
    "    table_properties={\"quality\": \"silver\"}\n",
    ")\n",
    "@dlt.expect(\"valid_confidence\",   \"confidence_score BETWEEN 0 AND 1\")\n",
    "@dlt.expect(\"valid_revenue\",      \"revenue_usd_millions > 0\")\n",
    "@dlt.expect(\"valid_gross_margin\", \"gross_margin_pct BETWEEN 0 AND 100\")\n",
    "def kpi_enriched():\n",
    "    df = spark.read.table(\"main.financial.extracted_kpis\")\n",
    "\n",
    "    # Deduplicate — keep latest extraction per ticker+quarter\n",
    "    window_dedup = Window.partitionBy(\"ticker\", \"quarter\") \\\n",
    "                         .orderBy(F.col(\"extraction_ts\").desc())\n",
    "\n",
    "    df = df.withColumn(\"row_num\", F.row_number().over(window_dedup)) \\\n",
    "           .filter(F.col(\"row_num\") == 1) \\\n",
    "           .drop(\"row_num\")\n",
    "\n",
    "    # Quarter date for window ordering\n",
    "    df = df.withColumn(\n",
    "        \"quarter_date\",\n",
    "        F.to_date(\n",
    "            F.concat(\n",
    "                F.split(F.col(\"quarter\"), \"-Q\").getItem(0),\n",
    "                F.lit(\"-\"),\n",
    "                (F.split(F.col(\"quarter\"), \"-Q\").getItem(1).cast(\"int\") * 3 - 2)\n",
    "                 .cast(\"string\"),\n",
    "                F.lit(\"-01\")\n",
    "            ),\n",
    "            \"yyyy-M-dd\"\n",
    "        )\n",
    "    )\n",
    "\n",
    "    # QoQ window\n",
    "    window_qoq = Window.partitionBy(\"ticker\").orderBy(\"quarter_date\")\n",
    "\n",
    "    df = df.withColumn(\n",
    "        \"revenue_qoq_delta_pct\",\n",
    "        F.round(\n",
    "            (F.col(\"revenue_usd_millions\") -\n",
    "             F.lag(\"revenue_usd_millions\").over(window_qoq)) /\n",
    "            F.lag(\"revenue_usd_millions\").over(window_qoq) * 100, 2\n",
    "        )\n",
    "    ).withColumn(\n",
    "        \"eps_qoq_delta_pct\",\n",
    "        F.round(\n",
    "            (F.col(\"eps_diluted\") -\n",
    "             F.lag(\"eps_diluted\").over(window_qoq)) /\n",
    "            F.abs(F.lag(\"eps_diluted\").over(window_qoq)) * 100, 2\n",
    "        )\n",
    "    ).withColumn(\n",
    "        \"margin_qoq_delta_pct\",\n",
    "        F.round(\n",
    "            F.col(\"gross_margin_pct\") -\n",
    "            F.lag(\"gross_margin_pct\").over(window_qoq), 2\n",
    "        )\n",
    "    )\n",
    "\n",
    "    # Rolling 4-quarter avg confidence\n",
    "    window_roll = Window.partitionBy(\"ticker\") \\\n",
    "                        .orderBy(\"quarter_date\") \\\n",
    "                        .rowsBetween(-3, 0)\n",
    "\n",
    "    df = df.withColumn(\n",
    "        \"avg_confidence_4q\",\n",
    "        F.round(F.avg(\"confidence_score\").over(window_roll), 3)\n",
    "    )\n",
    "\n",
    "    # Net income margin\n",
    "    df = df.withColumn(\n",
    "        \"net_income_margin_pct\",\n",
    "        F.round(\n",
    "            F.col(\"net_income_usd_millions\") /\n",
    "            F.col(\"revenue_usd_millions\") * 100, 2\n",
    "        )\n",
    "    )\n",
    "\n",
    "    return df\n",
    "\n",
    "\n",
    "@dlt.table(\n",
    "    name=\"peer_comparison\",\n",
    "    comment=\"KPIs joined with peer benchmarks and sector aggregates\",\n",
    "    table_properties={\"quality\": \"silver\"}\n",
    ")\n",
    "def peer_comparison():\n",
    "    kpis  = dlt.read(\"kpi_enriched\")\n",
    "    peers = spark.read.table(\"main.financial.peer_benchmarks\")\n",
    "\n",
    "    df = kpis.join(\n",
    "        peers.select(\n",
    "            \"ticker\", \"quarter\",\n",
    "            \"sector_median_margin\",\n",
    "            \"relative_rank\",\n",
    "            \"margin_delta_pct\",\n",
    "            \"peers_used\"\n",
    "        ),\n",
    "        on=[\"ticker\", \"quarter\"],\n",
    "        how=\"left\"\n",
    "    )\n",
    "\n",
    "    df = df.withColumn(\n",
    "        \"margin_premium_discount\",\n",
    "        F.round(F.col(\"gross_margin_pct\") - F.col(\"sector_median_margin\"), 2)\n",
    "    )\n",
    "\n",
    "    window_sector = Window.partitionBy(\"quarter\")\n",
    "\n",
    "    df = df.withColumn(\n",
    "        \"sector_avg_revenue_growth\",\n",
    "        F.round(F.avg(\"revenue_yoy_growth_pct\").over(window_sector), 2)\n",
    "    ).withColumn(\n",
    "        \"sector_avg_eps\",\n",
    "        F.round(F.avg(\"eps_diluted\").over(window_sector), 2)\n",
    "    ).withColumn(\n",
    "        \"revenue_vs_sector_avg\",\n",
    "        F.round(\n",
    "            F.col(\"revenue_yoy_growth_pct\") -\n",
    "            F.col(\"sector_avg_revenue_growth\"), 2\n",
    "        )\n",
    "    )\n",
    "\n",
    "    return df\n",
    "\n",
    "\n",
    "@dlt.table(\n",
    "    name=\"company_profile\",\n",
    "    comment=\"Company metadata with market cap tier\",\n",
    "    table_properties={\"quality\": \"silver\"}\n",
    ")\n",
    "def company_profile():\n",
    "    discovery = spark.read.table(\"main.financial.peer_discovery\")\n",
    "\n",
    "    window_latest = Window.partitionBy(\"ticker\") \\\n",
    "                          .orderBy(F.col(\"fetched_ts\").desc())\n",
    "\n",
    "    df = discovery.withColumn(\"row_num\", F.row_number().over(window_latest)) \\\n",
    "                  .filter(F.col(\"row_num\") == 1) \\\n",
    "                  .drop(\"row_num\") \\\n",
    "                  .select(\n",
    "                      \"ticker\",\n",
    "                      \"sub_industry\",\n",
    "                      \"log_market_cap\",\n",
    "                      \"ebitda_margin\",\n",
    "                      \"roic\",\n",
    "                      F.col(\"fetched_ts\").alias(\"profile_ts\")\n",
    "                  )\n",
    "\n",
    "    df = df.withColumn(\n",
    "        \"market_cap_tier\",\n",
    "        F.when(F.col(\"log_market_cap\") >= 25.3, \"mega_cap\")\n",
    "         .when(F.col(\"log_market_cap\") >= 23.0, \"large_cap\")\n",
    "         .when(F.col(\"log_market_cap\") >= 20.7, \"mid_cap\")\n",
    "         .otherwise(\"small_cap\")\n",
    "    )\n",
    "\n",
    "    return df"
   ]
  }
 ],
 "metadata": {
  "application/vnd.databricks.v1+notebook": {
   "computePreferences": null,
   "dashboards": [],
   "environmentMetadata": {
    "base_environment": "",
    "environment_version": "5"
   },
   "inputWidgetPreferences": null,
   "language": "python",
   "notebookMetadata": {
    "pythonIndentUnit": 4
   },
   "notebookName": "dlt_silver_pipeline",
   "widgets": {}
  },
  "language_info": {
   "name": "python"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 0
}