{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 0,
   "metadata": {
    "application/vnd.databricks.v1+cell": {
     "cellMetadata": {},
     "inputWidgets": {},
     "nuid": "bc9844ca-4fcc-4b4c-852e-6cacf9a2e1f6",
     "showTitle": false,
     "tableResultSettingsMap": {},
     "title": ""
    }
   },
   "outputs": [],
   "source": [
    "import dlt\n",
    "from pyspark.sql import functions as F\n",
    "from pyspark.sql.window import Window\n",
    "\n",
    "\n",
    "@dlt.table(\n",
    "    name=\"sector_scorecard\",\n",
    "    comment=\"Latest quarter all companies ranked — dashboard heatmap\",\n",
    "    table_properties={\"quality\": \"gold\"}\n",
    ")\n",
    "def sector_scorecard():\n",
    "    df = spark.read.table(\"main.financial_silver.peer_comparison\")\n",
    "\n",
    "    window_latest = Window.partitionBy(\"ticker\") \\\n",
    "                          .orderBy(F.col(\"quarter_date\").desc())\n",
    "\n",
    "    df = df.withColumn(\"row_num\", F.row_number().over(window_latest)) \\\n",
    "           .filter(F.col(\"row_num\") == 1) \\\n",
    "           .drop(\"row_num\")\n",
    "\n",
    "    metrics = [\n",
    "        \"revenue_usd_millions\",\n",
    "        \"eps_diluted\",\n",
    "        \"gross_margin_pct\",\n",
    "        \"net_income_margin_pct\",\n",
    "        \"revenue_yoy_growth_pct\",\n",
    "        \"confidence_score\"\n",
    "    ]\n",
    "\n",
    "    for metric in metrics:\n",
    "        df = df.withColumn(\n",
    "            f\"{metric}_rank\",\n",
    "            F.percent_rank().over(Window.orderBy(F.col(metric)))\n",
    "        )\n",
    "\n",
    "    return df.select(\n",
    "        \"ticker\", \"quarter\",\n",
    "        \"revenue_usd_millions\",       \"revenue_usd_millions_rank\",\n",
    "        \"eps_diluted\",                \"eps_diluted_rank\",\n",
    "        \"gross_margin_pct\",           \"gross_margin_pct_rank\",\n",
    "        \"net_income_margin_pct\",      \"net_income_margin_pct_rank\",\n",
    "        \"revenue_yoy_growth_pct\",     \"revenue_yoy_growth_pct_rank\",\n",
    "        \"relative_rank\",\n",
    "        \"margin_premium_discount\",\n",
    "        \"confidence_score\",\n",
    "        \"data_quality_flag\"\n",
    "    )\n",
    "\n",
    "\n",
    "@dlt.table(\n",
    "    name=\"time_series_kpis\",\n",
    "    comment=\"All companies all quarters — trend charts\",\n",
    "    table_properties={\"quality\": \"gold\"}\n",
    ")\n",
    "def time_series_kpis():\n",
    "    df = spark.read.table(\"main.financial_silver.kpi_enriched\")\n",
    "\n",
    "    return df.select(\n",
    "        \"ticker\",\n",
    "        \"quarter\",\n",
    "        \"quarter_date\",\n",
    "        \"revenue_usd_millions\",\n",
    "        \"net_income_usd_millions\",\n",
    "        \"eps_diluted\",\n",
    "        \"gross_margin_pct\",\n",
    "        \"net_income_margin_pct\",\n",
    "        \"revenue_yoy_growth_pct\",\n",
    "        \"revenue_qoq_delta_pct\",\n",
    "        \"eps_qoq_delta_pct\",\n",
    "        \"margin_qoq_delta_pct\",\n",
    "        \"avg_confidence_4q\",\n",
    "        \"data_quality_flag\",\n",
    "        \"confidence_score\",\n",
    "        \"retry_count\",\n",
    "        \"hitl_required\"\n",
    "    ).orderBy(\"ticker\", \"quarter_date\")\n",
    "\n",
    "\n",
    "@dlt.table(\n",
    "    name=\"peer_relative_performance\",\n",
    "    comment=\"Each company vs sector median — comparison charts\",\n",
    "    table_properties={\"quality\": \"gold\"}\n",
    ")\n",
    "def peer_relative_performance():\n",
    "    df = spark.read.table(\"main.financial_silver.peer_comparison\")\n",
    "\n",
    "    return df.select(\n",
    "        \"ticker\",\n",
    "        \"quarter\",\n",
    "        \"quarter_date\",\n",
    "        \"gross_margin_pct\",\n",
    "        \"sector_median_margin\",\n",
    "        \"margin_premium_discount\",\n",
    "        \"revenue_yoy_growth_pct\",\n",
    "        \"sector_avg_revenue_growth\",\n",
    "        \"revenue_vs_sector_avg\",\n",
    "        \"relative_rank\",\n",
    "        \"peers_used\",\n",
    "        \"eps_diluted\",\n",
    "        \"sector_avg_eps\"\n",
    "    ).orderBy(\"ticker\", \"quarter_date\")\n",
    "\n",
    "\n",
    "@dlt.table(\n",
    "    name=\"pipeline_health\",\n",
    "    comment=\"Pipeline run metrics — operational dashboard\",\n",
    "    table_properties={\"quality\": \"gold\"}\n",
    ")\n",
    "def pipeline_health():\n",
    "    df = spark.read.table(\"main.financial.extracted_kpis\")\n",
    "\n",
    "    df = df.withColumn(\"run_date\", F.to_date(\"extraction_ts\"))\n",
    "\n",
    "    return df.groupBy(\"run_date\", \"pipeline_version\").agg(\n",
    "        F.count(\"*\")                                         .alias(\"total_runs\"),\n",
    "        F.round(F.avg(\"confidence_score\"), 3)                .alias(\"avg_confidence\"),\n",
    "        F.round(F.avg(\"retry_count\"), 2)                     .alias(\"avg_retries\"),\n",
    "        F.sum(F.when(F.col(\"hitl_required\"), 1).otherwise(0)).alias(\"hitl_count\"),\n",
    "        F.sum(F.when(F.col(\"data_quality_flag\") == \"clean\", 1)\n",
    "               .otherwise(0))                                .alias(\"clean_count\"),\n",
    "        F.round(\n",
    "            F.sum(F.when(F.col(\"hitl_required\"), 1)\n",
    "                   .otherwise(0)) * 100.0 / F.count(\"*\"), 1\n",
    "        )                                                    .alias(\"hitl_rate_pct\"),\n",
    "        F.min(\"confidence_score\")                            .alias(\"min_confidence\"),\n",
    "        F.max(\"confidence_score\")                            .alias(\"max_confidence\"),\n",
    "    ).orderBy(\"run_date\")"
   ]
  }
 ],
 "metadata": {
  "application/vnd.databricks.v1+notebook": {
   "computePreferences": null,
   "dashboards": [],
   "environmentMetadata": {
    "base_environment": "",
    "environment_version": "5"
   },
   "inputWidgetPreferences": null,
   "language": "python",
   "notebookMetadata": {
    "pythonIndentUnit": 4
   },
   "notebookName": "dtl_gold_pipeline",
   "widgets": {}
  },
  "language_info": {
   "name": "python"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 0
}